import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localfont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const poppins = localfont({
  src: "../public/fonts/Poppins-Black.ttf",
  variable: "--font-poppins" // Setting variable property that will represent name of our font
  // It is a custome css property
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // openGraph: {              // this is used to share pages on social media
  //   title: '...',
  //   description: '...'
  // }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      {/* <body className={inter.className}> */}
      {/* <body className={roboto.className}> */}
      {/* <body className={poppins.className}> */}
      <body className={poppins.variable}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">
            {children}
            {/* <Suspense fallback={<p>Loading...</p>}>
        {children}
      </Suspense> */}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
